### ISSUE TITLE
Please read the docs for custom config before making an issue

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#1062]
Guys Ive seen this a lot that many of yall post the issue without understanding how nvchad works ( read from docs ) even tho the docs are short. I feel it as annoying now, 70% issues in the repo are cuz of that. Seeing such issues  just make me think like why did i even make the docs bruh :angry: :disappointed: 

Yesterday I had a scary nightmare, cant describe it but all i saw in it was "chadrc" haunting me like I was debugging the chadrc kinda and some weird things came out of the screen like bruh, Ik this sounds stupid but I couldnt remember much of that dream, it was scary that i couldnt sleep alone. Seeing tons of custom config issues spams it even in my dreams :disappointed_relieved:  . 

I was very happy at the removal of custom config before but i had to re-implement it as yall didnt like that decision. All I want you is reading the docs before posting the issues & learn basic lua. Lua's very important if you use latest neovim these days

**Comment by tomasky** [comment]
I known you feeling，sometimes I think about some problems and lose sleep, the `nvchad`  saves my time ,thanks for your effort

**Comment by chr0x6d** [comment]
@siduck I've read a large amount of issues and PRs in this repo and I can understand your frustration. You've done a ton of work in this repo and made neovim better for 1000s of people - but because of that now this repo is serious and affects 1000s of people so that is probably where some of your stress is coming from.

I think you and the top 5-10 contributors need to have an actual planning for what you want **2.0/3.0 NvChad to be**:
- Target User - is this repo for advanced-users only, or is it for the average neovim user who is able to write a bit of lua and read docs, but doesn't want to have configure everything(lazy-loading, hooking into LSP, etc.)?

- How to discourage low-effort issues - and if an automatic solution(bot) to deal with low-effort issues is needed

- custom config VS customless

- Development style - will 2.0/3.0 be slowly built up to by commits to 'main' branch?

- and 10+ other factors that I don't know about - since I'm not a top contributor

It would be best if you got the results of this in a markdown file, or github discussion or something, and then could refer back to it easily later. 

**Why you need to do a planning**
Right now this repo that has 1000s of daily users is having emotional and impulsive breaking changes pushed to it frequently - and breaking changes aren't necessarily bad, whats bad is that these changes don't seem to have an actual well thought-out destination

I think the entire `custom vs customless` situation is a perfect example of this - the top contributors were not aligned on anything and the discussion to change it was very sudden - big changes like this should be pre-planned to avoid stress and heated-discussions for both the maintainers and users

**I want to like NvChad, but the current haphazard way its being developed is making me look elsewhere - I think a lot of users are thinking similarly**

**Comment by motionlessrestore** [comment]
@siduck I've read a large amount of issues and PRs in this repo and I can understand your frustration. You've done a ton of work in this repo and made neovim better for 1000s of people - but because of that now this repo is serious and affects 1000s of people so that is probably where some of your stress is coming from.

I think you and the top 5-10 contributors need to have an actual planning for what you want **2.0/3.0 NvChad to be**:
- Target User - is this repo for advanced-users only, or is it for the average neovim user who is able to write a bit of lua and read docs, but doesn't want to have configure everything(lazy-loading, hooking into LSP, etc.)?

- How to discourage low-effort issues - and if an automatic solution(bot) to deal with low-effort issues is needed

- custom config VS customless

- Development style - will 2.0/3.0 be slowly built up to by commits to 'main' branch?

- and 10+ other factors that I don't know about - since I'm not a top contributor

It would be best if you got the results of this in a markdown file, or github discussion or something, and then could refer back to it easily later. 

**Why you need to do a planning**
Right now this repo that has 1000s of daily users is having emotional and impulsive breaking changes pushed to it frequently - and breaking changes aren't necessarily bad, whats bad is that these changes don't seem to have an actual well thought-out destination

I think the entire `custom vs customless` situation is a perfect example of this - the top contributors were not aligned on anything and the discussion to change it was very sudden - big changes like this should be pre-planned to avoid stress and heated-discussions for both the maintainers and users

**I want to use NvChad, but the current haphazard way its being developed is making me look elsewhere -  and I've seen many users echo this**

**Comment by siduck** [comment]
@motionlessrestore you are right, I have to stop treating nvchad like my own config even tho its a public config and used by thousands, I will maintain a dev branch from now

**Comment by siduck** [comment]
nvchad's for everyone if they read the docs , if they dont then bye bye!

**Comment by motionlessrestore** [comment]
@siduck Nice - everyone knows how hard you've worked on this project and then having to spend half your time replying to low-effort issues from people who didn't even read the docs is soul destroying - but that's just the way FOSS is if you don't have bots or strategies to handle it automatically.

**The Name**
This is probably the biggest breaking change of all - but maybe you and the top contributors could at least consider and vote on a name change for this entire project. Something with no associated meaning like the word "Chad" has.

Sure the name "NvChad" is cool and all, but when a co-worker in a professional setting asks about your vim config(and they will since NvChad looks cool enough for people to ask) - having to use the word "Chad" just feels wrong. Maybe before the next major release a new logo/name could be thought up for the entire project - I'll help with updating it in docs and all that if you make the decision.

Also I don't know if you're in a Software-Engineering job or not - but when an interviewer checks out your Github portfolio do you really want to have the word "Chad" everywhere? Having a repo with 9.4k stars might just make up for that though 😆

**Comment by siduck** [comment]
Lol I've used it only in 3 of my projects. BTW there Chad word here doesn't mean the guy Chad it's like Chad linux vs windows I.e means superior. Also nvchad was neovim-dotfiles before but it blew up quick and I couldn't think of a better name lol

**Comment by siduck** [comment]
Also I'm not a CS student but I intend to get a job in that field and people here don't know the Chad word so I'm gg xD

**Comment by motionlessrestore** [comment]
@siduck Well in your case I guess the name is not much of a problem 😆 Plus changing it would be a ton of work so its probably for the best to keep it as is
