### ISSUE TITLE
Add info text for which-key's first level menu

### ISSUE THREAD

**Issue by xarthurx** [NvChad/NvChad#1068]
The `<leaderuu` will update `nvChad`, but when pressing `<leader>` the first-level menu for `u` key is just "prefix".

I actually have other mappings with the format `<leader><key1><key2>`.
With the most recent mapping mechanism, is it possible to add text info for the `<key1>` when pressing `<leader>`?

![image](https://user-images.githubusercontent.com/1921878/168164224-0f838ddc-7760-47f0-9e96-0302c4760131.png)

**Comment by LeonHeidelbach** [comment]
@xarthurx you can only add text to these prefix options if there is an actual command mapped to the key combination. I don't think you can just add a text to prefixes alone.

![Screenshot_20220513_011232](https://user-images.githubusercontent.com/55194243/168182117-16c14a78-e06f-43e6-87be-cd2fbe486388.png)

**Comment by kaiserdrake** [comment]
@xarthurx 
How about the following?
<img width="800" alt="image" src="https://user-images.githubusercontent.com/77472407/168216240-777566a5-5881-41f1-aa60-1e2fbac11f75.png">

**Comment by siduck** [comment]
@kaiserdrake @xarthurx  that shows just prefix cuz we didnt map those keys, for example leader + c etc, So in the future we will add more mappings by filling up those places. So not an issue!

**Comment by kaiserdrake** [comment]
Yes, I thought the post was asking " is it possible to add text info for the <key1> when pressing <leader>"
Which I showed is possible.

But yes, this is not an issue.

**Comment by LeonHeidelbach** [comment]
> Yes, I thought the post was asking " is it possible to add text info for the `<key1>` when pressing `<leader>`"
> 
> Which I showed is possible.
> 
> 
> 
> But yes, this is not an issue.

Yes it is possible when adding a mapping to the key (just as I showed) but this will also run the command `+Gitsigns` in your example when pressing `<leader>g`, which is not necessarily like only adding a label and not expected behavior. If you would now press `<leader>g` quickly the prompt for all keys after `g` in the next level would not show up because it ran the associated command with that key map.

**Comment by SimonLammer** [comment]
In case anyone else stumbles across this issue, this has been solved in another issue: https://github.com/NvChad/NvChad/issues/1246#issuecomment-1817582042

**Comment by xarthurx** [comment]
> In case anyone else stumbles across this issue, this has been solved in another issue: [#1246 (comment)](https://github.com/NvChad/NvChad/issues/1246#issuecomment-1817582042)

For nvchad v2.5, we don't need such modifications any more.
Using the default `map()` is good enough to be integrated into Which-key.

**Comment by SimonLammer** [comment]
@xarthurx I'm not sure what what you mean. Could you please elaborate how I would use `map` to get rid of those `+prefix` descriptions in whichkey?

**Comment by xarthurx** [comment]
Go and check v2.5, and use the method from the doc.

V2.5 is a major release. Make sure you back up everything

**Comment by seflue** [comment]
> @xarthurx I'm not sure what what you mean. Could you please elaborate how I would use `map` to get rid of those `+prefix` descriptions in whichkey?

You don't use `map`, because `map` is actually an alias to `vim.keymap.set` and is called with the standard arguments to set neovim keybindings.

which-key can only identify the descriptions for actual mappings. For the groups it relies on it's own configuration. So @xarthurx comment, while not completely incorrect, is extremely vague and actually not very helpful, because in the NvChad documentation which-key is not mentioned with any custom configuration. You need to look into the original [which-key](https://github.com/folke/which-key.nvim?tab=readme-ov-file#%EF%B8%8F-mappings) documentation and (at least I did) into the actual NvChad code, [where the which-key plugin](https://github.com/NvChad/NvChad/blob/156eeef8ecae812acd79d5eb58070d734a6202c6/lua/nvchad/plugins/ui.lua#L77) is configured - to find out, that it is installed, but actually no groups are configured.

What I ended up with, was to set the which-key groups in my `mappings.lua` of the NvChad starter template (`$HOME/.config/nvim/lua/mappings.lua) like this:

```lua
-- ...
-- your normal mappings
-- ...

local groups = {
  c = { name = "🧔 [c]had" },
  f = { name = "🔍 [f]ind" },
  m = { name = "🔖 [m]arks"},
  -- ... add all your groups here  
}

require("which-key").register(groups, {prefix = "<leader>"})
```
Reasoning behind that: the `mappings.lua` is just included by the `init.lua` on startup, so I can write arbitrary code, which I want to be evaluated on startup. Since the which-key groups belong somehow to my key mappings, I decided to store them there.
But to be honest, as glossy and nice looking NvChad is from the visual side, I actually don't like the default keymaps from a usability perspective, because they aren't following consistent mnemonic groups. "f" often stands for "find" but sometimes for "file". There a some `<leader> + <keys1><key2>` mappings, where `<key1>` creates a group with just one mapping in it. No offense made to the plugin author, he did an amazing job in theming and nice visuals. But to make nvim comfortable out of the box, someone has to put actually a bit of effort in rebinding the keys.
And I didn't find out yet, where the groups in NvCheatSheet are defined, though I like the idea of a full-screen cheat sheet ...

**Comment by carlisia** [comment]
> > [@xarthurx](https://github.com/xarthurx) I'm not sure what what you mean. Could you please elaborate how I would use `map` to get rid of those `+prefix` descriptions in whichkey?
> 
> You don't use `map`, because `map` is actually an alias to `vim.keymap.set` and is called with the standard arguments to set neovim keybindings.
> 
> which-key can only identify the descriptions for actual mappings. For the groups it relies on it's own configuration. So [@xarthurx](https://github.com/xarthurx) comment, while not completely incorrect, is extremely vague and actually not very helpful, because in the NvChad documentation which-key is not mentioned with any custom configuration. You need to look into the original [which-key](https://github.com/folke/which-key.nvim?tab=readme-ov-file#%EF%B8%8F-mappings) documentation and (at least I did) into the actual NvChad code, [where the which-key plugin](https://github.com/NvChad/NvChad/blob/156eeef8ecae812acd79d5eb58070d734a6202c6/lua/nvchad/plugins/ui.lua#L77) is configured - to find out, that it is installed, but actually no groups are configured.
> 
> What I ended up with, was to set the which-key groups in my `mappings.lua` of the NvChad starter template (`$HOME/.config/nvim/lua/mappings.lua) like this:
> 
> -- ...
> -- your normal mappings
> -- ...
> 
> local groups = {
>   c = { name = "🧔 [c]had" },
>   f = { name = "🔍 [f]ind" },
>   m = { name = "🔖 [m]arks"},
>   -- ... add all your groups here  
> }
> 
> require("which-key").register(groups, {prefix = "<leader>"})
> Reasoning behind that: the `mappings.lua` is just included by the `init.lua` on startup, so I can write arbitrary code, which I want to be evaluated on startup. Since the which-key groups belong somehow to my key mappings, I decided to store them there. But to be honest, as glossy and nice looking NvChad is from the visual side, I actually don't like the default keymaps from a usability perspective, because they aren't following consistent mnemonic groups. "f" often stands for "find" but sometimes for "file". There a some `<leader> + <keys1><key2>` mappings, where `<key1>` creates a group with just one mapping in it. No offense made to the plugin author, he did an amazing job in theming and nice visuals. But to make nvim comfortable out of the box, someone has to put actually a bit of effort in rebinding the keys. And I didn't find out yet, where the groups in NvCheatSheet are defined, though I like the idea of a full-screen cheat sheet ...

This is imo the best solution for where to place whichkey customizations! Thank you!

In case it helps anyone, whichkey v3 requires a slightly different format, **see below**. Nvchad v2.5 is pins whichkey to `main`, so if you   are up-to-date then you are using this version as well.

```
local groups = {
  { "<leader>c", group = "🧔 [c]had" },
  { "<leader>f", group = "🔍 [f]ind" },
  { "<leader>m", group = "🔖 [m]arks" },
  -- ... add all your groups here
}
require("which-key").add(groups)
```

Btw, the answer to "where to put things" changes a lot, it would be wonderful if the docs had a section for that with reach release that modifies it. "Read the entire nvchad doc" is not a helpful answer, especially when the answer is no where. My workflow for deciphering nvchad is: 1. read the docs multipe times, 2. read the source code, 3. look at other ppl's dotfiles. I do this because I ❤️ nvchad.

**Comment by siduck** [comment]
@carlisia the whichkey config, its obvious to put it in the config function of whichkey plugin!  

```lua
{
    "blabla whichkey",
     config = function()
            -- put here
            require("which-key").setup({}) -- needed cuz you're using config func which lazy discourages to, it says to use opts = {}
     end
}
