### ISSUE TITLE
restart nvim after updating nvchad 

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#1136]
Restart nvim after you do leader up + PackerSync to see the changes

**Comment by LeonHeidelbach** [comment]
Since we made changes to the way that LSP mappings are registered, running `<leader>uu` or `:NvChadUpdate` with a subsequent `:PackerSync` will not suffice. You will have to restart your nvim and then run `:PackerSync` manually for the mappings to apply correctly.

**Comment by nullchilly** [comment]
Hi, I run a fork of nvchad

Pretty much the same logic (I think) from [nvchad packer.lua](https://github.com/NvChad/NvChad/blob/main/lua/core/packer.lua) to [my plugins.lua](https://github.com/nullchilly/dots/blob/main/.config/nvim/lua/plugins.lua)

Almost half of the config doesn't load (Most importantly whichkey). I can always load them manually though, I wonder if you guys did some black magic to call VimEnter autocmds again?

To test on NvChad I modify the xdg values: `export XDG_CONFIG_HOME=/tmp XDG_DATA_HOME=/tmp && rm -rf /tmp/nvim && git clone https://github.com/NvChad/NvChad /tmp/nvim && nvim -nu /tmp/nvim/init.lua`

To test mine I found a way to clone subdirectory only: `export XDG_CONFIG_HOME=/tmp XDG_DATA_HOME=/tmp && rm -rf /tmp/nvim && svn export https://github.com/nullchilly/dots.git/trunk/.config/nvim /tmp/nvim && nvim -nu /tmp/nvim/init.lua`

Extra question: I wonder if people use docker for this (I didn't because I thought of fonts issues?)

**Comment by LeonHeidelbach** [comment]
@nullchilly if you are on our latest commit the reason for why `which-key` is no longer working for you is that we changed our `which-key` [configuration](https://github.com/NvChad/NvChad/blob/f8b5571466173f6518ab22351bacda186fd23b2e/lua/plugins/configs/whichkey.lua) in order to allow for LSP mappings to only be loaded when an LSP is actually attached to the buffer through `lspconfig`.

In your `plugins.lua` you will have to load `which-key` like this now:

```lua
 ["folke/which-key.nvim"] = {
    opt = true,
    setup = function()
       nvchad.packer_lazy_load "which-key.nvim"
    end,
    config = function()
       require("plugins.configs.whichkey").setup()
    end,
 },
``` 
@siduck  might be able to help you understand why your other plugins don't load.

**Comment by siduck** [comment]
@LeonHeidelbach  Users are supposed to control whole of nvchad with the custom config only ( chadrc to be more precised ) , i dont think i can help with nvchad forks :c , if the users are able to reproduce any issues they face with vanilla nvchad + minimal custom config then we'll look into the issue

**Comment by nullchilly** [comment]
Sadge, I just wanted to have my config loads on the first install .-. (Everything works properly after reloading)

And I basically compile nvchad's packer into one plugins.lua. Sigh, I will look more into it then.

**Comment by LeonHeidelbach** [comment]
@nullchilly Although I do understand your frustration, I have to agree with @siduck. Finding issues within a user maintained fork of NvChad is unfortunately out of our scope of operation and would take too much time out of actually developing NvChad if everyone were to submit issues like this. Maybe try to apply your custom changes (if you think it is absolutely necessary to apply them outside of the custom folder) to a fresh fork of the working main repo.

**Comment by siduck** [comment]
@nullchilly why not use the custom config tho? :thinking:

**Comment by nullchilly** [comment]
I solved it 🗡️ 

You need `setup = function() lazy "which-key.nvim" end`
And not `setup = lazy "which-key.nvim"`. I still don't know why that's the case though, packer prompt nil value when neovim called the first time ever and works fine on the second time...
