### ISSUE TITLE
Make NvChad/NvChad repo a template

### ISSUE THREAD

**Issue by sudipghimire533** [NvChad/NvChad#1222]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Make [NvChad/NvChad](https://github.com/NvChad/NvChad) repo a template repo.

**Describe alternatives you've considered**
- None

**Additional context**
Most of us use NvChad as a base config (I guess that's what NvChad intend to be ) before we fully personalized to our preference. While everything works just great, it would be even more handly if we can make this repo a template. This will allow anyone to easily make their config completely their's.

**Screenshot**
- Not applicable

**Comment by siduck** [comment]
Im not sure what a template repo means :thinking:

**Comment by tomasky** [comment]
Maybe like custom nvchad dotfiles:

http://github.com/siduck/dotfiles/tree/master/nvchad

**Comment by sudipghimire533** [comment]
Template repo is basically a marker in github repo. By marking a repo as a template template:
- A use this template will appear in github ui like this:
![image](https://user-images.githubusercontent.com/39845901/174233537-3c4ed0bf-c515-456c-8575-d7d5d264616f.png)
- When someone does `use this template`, it will basically clone this repo's single branch, rewrite git history with single commit. It is more or less similar to cloning repo but bit cleaner for this purpose.

Github docs:
- https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository
- https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template

**Comment by LeonHeidelbach** [comment]
@sudipghimire533 I don't think this is useful for NvChad since it is not meant to be a static base configuration that you clone once and update yourself afterwards. It is rather mean to be a dynamic baseline config that you can configure to your needs using the custom directory while still being able to keep it updated using the NvChadUpdate functionality. If you then decide, that you don't want that, you can use the new NvChadSnapshot feature, which will create a "one commit only" snapshot branch in the author's name that can no longer be updated and freezes all packages using a `PackerSnapshot`. You can add as many changes as you like in there if you decide to do so and switch between snapshot configurations. You can learn more about how this works here #1221.

**Comment by siduck** [comment]
i agree with lioin

**Comment by sudipghimire533** [comment]
Ummhmm. `PackerSnaphshot` was something I was not expecting. And you aremaking low key sense @LeonHeidelbach . I am actually just starting with NvChad and this was the first thing I felt missing. Anyway I hope I will have great experience with NvChad. Thanks to awesome developers :)
