### ISSUE TITLE
Updating NvChad fails on Windows

### ISSUE THREAD

**Issue by sitiom** [NvChad/NvChad#1300]
**Describe the bug**
Updating NvChad fails on Windows, I get this error instead:
```
Error running command:
git -C C:\Users\rycaeli\AppData\Local\nvim checkout main
Error message:

Checking out branch main failed! Current branch is: .
```

**To Reproduce**
1. Install NvChad on Windows
2. `<leader>uu`

**Expected behavior**
It is supposed to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/56180050/176982468-8d4e82c1-60fb-4075-85a8-a7aad6585439.png)

**Desktop (please complete the following information):**
 - Windows 11
 - Windows Terminal
 - v0.7.2

**Comment by siduck** [comment]
@LeonHeidelbach D:

**Comment by LeonHeidelbach** [comment]
@sitiom @siduck I cannot reproduce this behaviour. Everything works just fine on Linux and MacOs on my machines. Unfortunately I don't have a machine running Windows 11 to test with. Did you try this with a clean fresh install of NvChad? Try running a manual `PackerSync` and let me know if this persists. Could you also try to update your version of git? Since I didn't change anything on the updater for the past weeks and we have quite a few Windows, it's very strange that no-one else had this issue before.

**Comment by sitiom** [comment]
> Did you try this with a clean fresh install of NvChad?

Yes.

> Everything works just fine on Linux and MacOs on my machines.

Yes, it does. I have specified on my title that it is a Windows issue.

> Try running a manual PackerSync and let me know if this persists. 

`PackerSync` works, `NvChadUpdate` doesn't.

> Could you also try to update your version of git?

My git is already in the latest version:
```console
> git --version
git version 2.37.0.windows.1
```

> Since I didn't change anything on the updater for the past weeks and we have quite a few Windows, it's very strange that no-one else had this issue before.

Yep, it was working some time before I updated it today.

**Comment by LeonHeidelbach** [comment]
@sitiom @siduck I have spun up my old Windows 10 partition and found out that this issue seems to be specific to the `mingw64` i.e. the `git bash` terminal. On the following screenshot you can see the `git bash` terminal on the top left, followed by the `nvim-qt` standalone app, followed by windows's own cmd and even powershell on the bottom right. No other terminal emualtor seems to have this issue. It seems that `mingw64` cannot locate the `bash` executable for some reason. This is very weird.

![image](https://user-images.githubusercontent.com/55194243/176995583-64027d6b-65e7-465b-9594-0df685f15848.png)

**Comment by sitiom** [comment]
I don't even use git bash. I use PowerShell Core but how come it is linked to that?

**Comment by sitiom** [comment]
@LeonHeidelbach This issue shouldn't be closed as it should be fixed to work on all shells.

**Comment by LeonHeidelbach** [comment]
@sitiom As you can see from the error message below, nvim appends a `/s` to the internal call to bash made by nvim through it's terminal command API i.e. `/usr/bin/bash /s` and on mingw64 this apparently causes this issue. We really cannot do anything about this, so this is not a NvChad issue. We can only use the nvim command API to issue terminal commands so we cannot patch this. You can see on my screenshot that I used the standard PowerShell and everything worked fine. Did you try any other terminal emulator?

```terminal
Error running command:
git -C C:\Users\Leon\AppData\Local\nvim checkout main
Error message:
/usr/bin/bash: /s: No such file or directory

Checking out branch main failed! Current branch is: .
Press ENTER or type command to continue
```

**Comment by sitiom** [comment]
As I said before, I use PowerShell Core and not git bash. But as it turns out, it has to do something with my `$env:SHELL` variable. I have it set to `pwsh -NoLogo`. But if I unset it, it works. Perhaps there is something you can fix here?

**Comment by LeonHeidelbach** [comment]
@siduck @sitiom As you can see [here](https://github.com/NvChad/extensions/blob/5dd1b3518fabb027d4ed9d29080ca43f8dd1a65c/lua/nvchad/init.lua#L39), this is the extent to which we have control over issuing terminal commands. It's a simple call to the builtin nvim function `vim.fn.system`, and [here](https://github.com/NvChad/extensions/blob/5dd1b3518fabb027d4ed9d29080ca43f8dd1a65c/lua/nvchad/utils/git.lua#L104) you can see how I implemented a wrapper to call the `git checkout` command, so that we can handle errors in case any occur. Unfortunately this is something that has to be fixed/handled in the Neovim project itself or your terminal emulator. Although I have to admit it is really strange that this particular issue only occurs on some emulators but not on others. Maybe @zbirenbaum has an idea on how to mitigate this issue from our side.

**Comment by sitiom** [comment]
I've seen similar issues before. I think the solution was to wrap the command around `cmd /c "<command>"` ([Example](https://github.com/neovim/nvim-lspconfig/blob/057ca6b7f5312f323eb7212f9282ed723560bc3f/lua/lspconfig/server_configurations/angularls.lua#L25-L27)). Would that be the case for this one?

**Comment by sitiom** [comment]
Yep, seems to have solved it:
![image](https://user-images.githubusercontent.com/56180050/176997683-f1993ee3-ee26-41ba-9491-8333fb08715e.png)
![image](https://user-images.githubusercontent.com/56180050/176997694-c07fe371-4779-424b-ad51-d2e900de0871.png)

**Comment by sitiom** [comment]
@LeonHeidelbach https://github.com/NvChad/extensions/commit/d6e09c448803480a1fd1f7d0545aec147b95a256 still won't work because if the argument is passed as a string, it still runs through `&shell` (See `:h system()`). It has to be a list like the one above.

**Comment by LeonHeidelbach** [comment]
@sitiom It should work now. Nice catch in the lsp-config code. :)

**Comment by sitiom** [comment]
@LeonHeidelbach Um, I think you would have to fix the update function too.
![image](https://user-images.githubusercontent.com/56180050/177000903-1186724c-2756-4a88-9b42-64b5384b365f.png)
