### ISSUE TITLE
Plugins not loading (packer status of "not loaded" for most)

### ISSUE THREAD

**Issue by jamesla** [NvChad/NvChad#1430]
**Describe the bug**
Most plugins are not working - when I run `:PackerStatus` I get the following resuults

<img width="616" alt="image" src="https://user-images.githubusercontent.com/5243178/183222437-c416236a-16a4-4af7-843a-b8e52bffb4f7.png">

**To Reproduce**
1. Open vim
2. Press space (vim telescope bind)
3. nothing happens
4. Run :PackerStatus and notice that most plugins are not loading

**Expected behavior**
I would expect that most of these plugins should be loading?

**Desktop (please complete the following information):**
 - Operating System: Nixox
 - Terminal: st
 - Version of Neovim: 0.72

**Comment by siduck** [comment]
thats normal , we are lazyloading to the finest now

**Comment by kamalkech** [comment]
@siduck  cannot understand ur last comment !!

**Comment by siduck** [comment]
> @siduck cannot understand ur last comment !!

we lazyload plugins, this means that not all plugins will be loaded when you open neovim thats because plugins will be loaded only when needed. dont worry about it 

for example telescope doesnt need to be loaded on startup so we load it on specific commands ( `Telescope` ) , so when you run `Telescope` command for the first time, telescope pluguin gets loaded. 

Lazyloading plugins saves lots of startuptime and improves the loading speed of neovim

**Comment by defau1t** [comment]
Sorry to jump on another issue but is there a list of "how to enable plugin" commands? which-key isn't loading for me
