### ISSUE TITLE
PackerSync nvchad_ui error

### ISSUE THREAD

**Issue by kola-web** [NvChad/NvChad#1525]
![image](https://user-images.githubusercontent.com/46446884/187590633-1b95e6b7-e315-40cd-b444-2f98c2a22e21.png)

**Comment by siduck** [comment]
not possible unless you're messing up tabufline with your own functions

**Comment by hockeymikey** [comment]
I saw this too if you have tabufline enabled (lazyload false) and you have override_module to nil. Delete the override line and should be fine. Only saw this in opening new files, existing ones are fine.

**Comment by siduck** [comment]
> I saw this too if you have tabufline enabled (lazyload false) and you have override_module to nil. Delete the override line and should be fine. Only saw this in opening new files, existing ones are fine.

if override is set to nil then why even add it?

**Comment by hockeymikey** [comment]
@siduck I don't know, that's what other people had. You don't have any good guides or tutorials that show me examples so I'm forced to go off random configs from other people.

**Comment by siduck** [comment]
> @siduck I don't know, that's what other people had. You don't have any good guides or tutorials that show me examples so I'm forced to go off random configs from other people.

what are you trying to do? also is your nvchad upto date?

**Comment by hockeymikey** [comment]
@siduck Overriding tabufline to load it right away everytime. And I was going to do the same with nvimtree, but then I decided against (and never could get it working). Yes, it's always up to date. I use the AUR package and update it pretty often.

**Comment by siduck** [comment]
> @siduck Overriding tabufline to load it right away everytime. And I was going to do the same with nvimtree, but then I decided against (and never could get it working). Yes, it's always up to date. I use the AUR package and update it pretty often.

hmm and what did u do till now?

**Comment by hockeymikey** [comment]
@siduck Nothing, I just ran defaults. This was my first dive into the configs and making it how I want (mostly because I wanted https://github.com/benizi/vim-automkdir installed and just led me down the rabbit hole). So I would say my experience is one of a new user and it's pretty poor, which isn't a diss by any means but just a comment on it objectively. I'm a software developer and if I'm having trouble spending hours figuring it out, scanning old issues and obscure comments, that says something and others probably will have a much harder time (or will open issues for help which clogs up your time I would think). Way more example configs showing the right way to do stuff would be the experience that would've helped me. I tried searching github for other's configs and that actually kinda helped, but it was a mix bag finding ones updated and helped in my case even with well curtailed search parameters.

**Comment by siduck** [comment]
@hockeymikey better ask it in our community i.e discord, telegram or matrix. many can help you there in my absence

**Comment by siduck** [comment]
`['benizi/vim-automkdir'] = {}` in custom plugins table

**Comment by hockeymikey** [comment]
@siduck Agreed. Thanks for that, I already have everything setup though. I'm good for now, just wanted to detail my experience for feedback, you know.
