### ISSUE TITLE
Error calling RustOpenExternalDocs

### ISSUE THREAD

**Issue by axdank** [NvChad/NvChad#1688]
hello, me again 😆. I tried to call RustOpenExternalDocs (from the rust-tools.vim plugin) and I got this error that I can't identify why it occurs.

command:
![imagen](https://user-images.githubusercontent.com/55039048/202821012-246dd5fa-66dc-4061-80a5-eb7cbd658bc3.png)

error returned:
![imagen](https://user-images.githubusercontent.com/55039048/202821044-6a49e658-9640-4a79-84c6-816cd41b05ce.png)

these lines of code are the ones executed in the plugin
https://github.com/simrat39/rust-tools.nvim/blob/99fd1238c6068d0637df30b6cee9a264334015e9/lua/rust-tools/external_docs.lua#L5-L16

I don't know if it's a bug inside NvChad or an error in the activation of one of the internal plugins, or something else.

**Comment by siduck** [comment]
netrw is disabled by default so enable it 

```lua

local enable_providers = {
  "netrw",
  "netrwPlugin",
  "netrwSettings",
  "netrwFileHandlers",
}

for _, plugin in pairs(enable_providers) do
  vim.g["loaded_" .. plugin] = nil
  vim.cmd("runtime " .. plugin)
end
```

in your custom/init.lua

**Comment by hockeymikey** [comment]
@siduck 
Thanks for the feedback. Two things: can you include this in the docs, because it took me hours of searching around to find this which should be well documents. Two: Why is this clunky format used instead of the default_plugins override as defined before in say: https://github.com/NvChad/NvChad/issues/1168#issuecomment-1145270844
This is just ugly and intuitive.  https://github.com/NvChad/NvChad/commit/9e3a43302c57d61f78b21e6f565d8026f5bd8d19 I have no idea why you reverted this implementation a day later. Two lines is cleaner on your end than many on ours.

**Comment by siduck** [comment]
@hockeymikey ok i'll include it here https://github.com/NvChad/nvchad.github.io/pull/118
