### ISSUE TITLE
Bug on running :so $MYVIMRC. `j` and `k` display weird mapping.

### ISSUE THREAD

**Issue by samuelnihoul** [NvChad/NvChad#1790]
https://vi.stackexchange.com/questions/40215/weird-command-characters-when-i-press-k-or-j-after-running-source-myvimrc

**Comment by samuelnihoul** [comment]
The steps to reproduce are:

1. Clean NVChad install
2. Edit init.lua
3. Run :so $MYVIMRC
4. press j or k in a file.

**Comment by siduck** [comment]
hi @samuelnihoul , can you go to core/default_mappings.lua file and commnt these lines? reopen nvim to see the change

![image](https://user-images.githubusercontent.com/59060246/220625744-7bfddbdf-d9c3-4343-ab34-849fb181d41a.png)

**Comment by samuelnihoul** [comment]
The issue is gone when commented out.

**Comment by samuelnihoul** [comment]
... but now I also have the issue on pressing j or k even though I commented your similar remaps (called t and x)

![image](https://user-images.githubusercontent.com/69475809/221413595-4a878eeb-2109-4b79-81b2-61f203037f2c.png)

**Comment by siduck** [comment]
this is weird,  which terminal are you using?

**Comment by siduck** [comment]
and feel free to as on our discord server etc, some users might able to help  u

**Comment by samuelnihoul** [comment]
I am using Powershell and Neovim-qt. I will join the Discord. By the way about my last comment, I think commenting the t and x remaps temporarily fixed it actually.

**Comment by siduck** [comment]
@samuelnihoul i made the change in v2.0, it'll release within few days

**Comment by LeonHeidelbach** [comment]
@siduck Removing these key maps is not a good idea as they are an essential improvement over the default behavior. I would rather try and fix the issue. I would also strongly recommend that you add issue templates that require users to provide a default set of information as I've started doing in [my plugin repo](https://github.com/LeonHeidelbach/trailblazer.nvim/issues/new/choose). You could just copy my template and adjust it a little. I have noticed that this greatly improves issue quality and makes diagnosing/resolving issues much easier and faster.

> ... but now I also have the issue on pressing j or k in line visual mode even though I commented your similar remaps (called t and x)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/69475809/221413595-4a878eeb-2109-4b79-81b2-61f203037f2c.png)
> 

The issue seems to be that the key map is recognized as a command ˋ<cmd>ˋ expression that should be executed on the current selection when in visual mode which requires a `<CR>` at the end. I have personally never had this issue in visual mode though so this might be specific to your user config @samuelnihoul. Are you currently using NvChad v.2.0 or are you on the `main` branch?

**Comment by siduck** [comment]
you are right @LeonHeidelbach, I honestly didnt understand what those mappings did. Seems like its a terminal issue for @samuelnihoul

**Comment by LeonHeidelbach** [comment]
Also @samuelnihoul why are you manually sourcing your `vimrc`? You should not do that when using NvChad.

**Comment by siduck** [comment]
> Also @samuelnihoul why are you manually sourcing your `vimrc`? You should not do that when using NvChad. If the issue resolves itself if you don't do this, we found the culprit. Some code in you `vimrc` interferes with NvChad.

oh I remember now, sourcing vimrc had given me the same error before

**Comment by siduck** [comment]
also @LeonHeidelbach myvimrc would just return the the path for init.lua 
![image](https://user-images.githubusercontent.com/59060246/221450431-98fbbe46-d32d-4908-8c50-292bc6a75dac.png)

**Comment by siduck** [comment]
so yea reloading nvim configs mustnt be done @samuelnihoul

**Comment by RS2-CN3** [comment]
hello, i was facing the same issue when i was trying to remap <leader>s to relaod my configs and figured out that manually sourcing config file was the culprit. 

But is there at least a way to reload my keymaps after i have edited them? For now i am closing all my neovim instance and reopening them when i add/remove/edit a keymap.
