### ISSUE TITLE
No way to remap all modes at once

### ISSUE THREAD

**Issue by etokheim** [NvChad/NvChad#1799]
Hi, guys, thanks for working on this awesome project!

I'm trying to move to NvChad, but I'm struggeling with mapping all modes (insert, visual etc) at once. Is there a good way to do that?

I use Colemak, so I want to remap hjkl in all modes at once.

The [docs](https://nvchad.com/config/Mappings) states that the way to remap keys is to create a config file in `lua/custom/mappings`, with a table corresponding to the mode the mapping should be active in. Ie.:

```lua
M.abc = {

  n = { -- Normal mode
     ["<C-n>"] = {"<cmd> Telescope <CR>", "Open Telescope"}
  }

  i = { -- Insert mode
    -- more keys!
  }
}
```

Also from the docs:
> You need to put your mappings into modes like n, v, i, t, etc.

But how would I go about mapping all modes at once?

In other words I need something equivalent to my old config:
```lua
local keymap = vim.api.nvim_set_keymap
-- Colemak - Swaps pnei to hjkl
keymap('', 'p', 'h', options)
keymap('', 'P', 'H', options)
keymap('', 'n', 'j', options)
keymap('', 'N', 'J', options)
keymap('', 'e', 'k', options)
keymap('', 'E', 'K', options)
keymap('', 'i', 'l', options)
keymap('', 'I', 'L', options)
...
```

I have another question as well – the config above seems to work fine together with NvChad. Why would I want to use the NvChad way, instead of the more standard approach? I suspect it's in order to avoid conflicts, but the docs doesn't mention it. Does that mean the above approach is not supported, or discouraged?

I'm currently leaning towards using the old way (above) for mapping the global mappings, then convert the mode specific mappings to the NvChad way. But do I even need to convert them?

Any pointers are greatly appreciated!

**Comment by lucario387** [comment]
it's generally fine ? But 
- Keymaps are defined this way to more easily be mapped to `which-key.nvim`, 
- Not all keymaps are loaded on startup, so you may need to remap again 

anyhow, @siduck, your call

**Comment by siduck** [comment]
i will give it a try  in 1-2 days

**Comment by siduck** [comment]
it'll add some complexity to our mapping functions imo ( core.utils.lua )  so I dont consider adding this feature, However you can just use the `vim.keymap` function as those mappings dont need description etc in `custom/init.lua`


Nvchad's way of creating mappings will make sure that they get shown in our cheatsheet window ( v2.0 feature )

![image](https://user-images.githubusercontent.com/59060246/223633288-22e79557-6cd9-4954-b230-0b56a2214b81.png)

**Comment by eljamm** [comment]
First, I'd like to thank all contributors and maintainers for this great project. I'm currently having a blast configuring my setup 🚀

The simplest and cleanest solution I could find for this was to copy the `keys` for each `mode` in a new array, which can be achieved using the following function in the user mappings:

```lua
-- Map keys for multiple modes
local multimap = function(section)
  local mappings = { plugin = section.plugin }
  local keys = section.keys

  for _, mode in ipairs(section.mode) do
    mappings[mode] = keys
  end
  return mappings
end
``` 

Creating a new array is necessary here since we don\'t want any extra elements (like `keys`) to get passed to the main mapping function, but we also want the mapping to look good in the configs.

I chose the following structure because it looked nice to me, but it can be changed by modifying the `multimap` function.

```lua
M.leap = multimap {
  mode = { "n", "x", "o" },
  keys = {
    ["s"] = { "<Plug>(leap-forward)", "Leap Forward" },
    ["S"] = { "<Plug>(leap-backward)", "Leap Backward" },
    ["gs"] = { "<Plug>(leap-from-window)", "Leap From Window" },
  },
}
```

One caveat for this approach is that the `keys` element is copied as reference to the rest of the modes, which doesn't cause any issues as far as I can tell, but it's still worth mentioning. 

As such, the final table that would be passed to the main mapping function is:

```lua
leap={
  n = <1>{
    S = { "<Plug>(leap-backward)", "Leap Backward" },
    gs = { "<Plug>(leap-from-window)", "Leap From Window" },
    s = { "<Plug>(leap-forward)", "Leap Forward" }
  },
  o = <table 1>,
  x = <table 1>
}
```

If you guys like this approach, we can add it to the docs or as a note for anyone who might be interested in doing this.

---

**Note:** Although I has some success incorporating this in NvChad's main mapping function, this approach already plays nicely with the default method of mapping and creating the cheatsheet. Plus, it's probably cleaner this way, too.
