### ISSUE TITLE
coq.nvim option

### ISSUE THREAD

**Issue by zbirenbaum** [NvChad/NvChad#302]
Right now completion is done through compe, but this repo: https://github.com/ms-jpq/coq_nvim made big waves on reddit the other day supposedly being by far the fastest completion engine available. Given that most glitches/performance issues I have had have been compe related, I think it would be worthwhile to look into having a switch in user config or something to select the completion engine you use.

Apparently treesitter support needs work, so I wouldn't straight up replace compe quite yet.

**Comment by G-Rowell** [comment]
I think given that it doesn't properly have treesitter support & it requires a system dependency of `python3-venv` (instead of a NeoVim dependency),
we would be unlikely to move to this, as we'll be trying to heavily limit any such system requirements

[Install
Needs python virtual env](https://github.com/ms-jpq/coq_nvim#install)
`apt install --yes -- python3-venv`

Though I do acknowledge this dependency is pretty basic.

We're more than happy to have a discussion on this though, I don't want to strongarm anything! :laughing:

**Comment by siduck76** [comment]
@zbirenbaum NvChad comes with nvim-compe by default , We couldve chosen completion-nvim ,nvim-cmp ,coc as well but compe has good support for luasnip which is needed. I guess its upto the user to use whatever completion engine gets used. We'll think about coq.nvim when we get issues with compe or maybe in the future.
