### ISSUE TITLE
PackerSync not found at install

### ISSUE THREAD

**Issue by b3b00** [NvChad/NvChad#336]
Hello, I am new to nvchad (in fact to neovim) When I 've tried to install nvChad : 

1. clone to .config/nvim is ok
2. then starting "nvim +'hi NormalFloat guibg=#1e222a' +PackerSync" makes an error 

E492: Commande inconnue: PackerSync (in french, I guess english is somethin like E492: "Command not found: PackerSync"

Environment : 
  - Win 10 
  - Windows terminal
  - git bash
  - neovim v0.5.0

**Comment by Oscuro1111** [comment]
same issue

**Comment by siduck76** [comment]
I doubt if those commands will work on windows :l

**Comment by siduck76** [comment]
check the windows section here https://nvchad.netlify.app/getting-started/setup/

**Comment by G-Rowell** [comment]
Hi @b3b00,

You say that `clone to .config/nvim is ok` works,

but this shouldn't really work if you are running Windows 10, are you running WSL2?

I get the impression we are missing some information maybe?

Though I do agree with SiDuck, many tools won't support Windows, so that could be an issue. It's tricky to debug from our side of course.


Hope we can find a solution,
G

**Comment by b3b00** [comment]
Hello,

Ok , i get it to install packages (expect telescope , I guess I miss fzf or ripgrep but that's another issue).
@siduck76 maybe you could clarify the windows setup part to explain what is the nvim folder where to copy init.lua and lua/
: ~/AppData/local/nvim.
that may be not that  obvious for neovim beginners.

**Comment by siduck76** [comment]
@b3b00 I added the windows section yesterday,  feel free to PR if there's something wrong in it.
