### ISSUE TITLE
Titles Aren't Above Respective Panes

### ISSUE THREAD

**Issue by fabio-pardo** [NvChad/NvChad#365]
I like to use nvim with split panes. Vertically and horizontally. However, when I split, the tab titles stay above the main pane. Is there a way to fix it?

![Screen Shot 2021-08-24 at 11 29 20 AM](https://user-images.githubusercontent.com/25315344/130645497-a5f20859-c8dc-4e0c-b2f3-3c19db6464c8.png)

**Comment by G-Rowell** [comment]
Hi @fabio-pardo ,

I don't think there would be any straightforward solution to this, as [`bufferline.nvim`](https://github.com/akinsho/nvim-bufferline.lua) doesn't support gaps of that kind between the labels.

Maybe have a look into the docs/code of bufferline? I unfortunately don't think there would be an easy fix for NvChad to do this.

My other suggestion would be to use two separate terminal emulator windows, I do it myself, and this problem is likely exacerbated by your screen resolution (which seems to be quite high, v. jealous!)

Hope this info is helpful


G

**Comment by G-Rowell** [comment]
Wish I had a better answer for you :disappointed: 
soz

**Comment by siduck76** [comment]
This looks more of a bufferline issue than nvchad's! maybe check their docs / make an issue there.

**Comment by fabio-pardo** [comment]
Ah.... I'll take a look there then! thank you for the quick response 😄 
Closing this but may follow it up with a response/solution I may find in the future.
