### ISSUE TITLE
Hidden terminal buffer comes back and locks buffer switch

### ISSUE THREAD

**Issue by marwan38** [NvChad/NvChad#413]
**Describe the bug**
A hidden terminal buffer gets activated after closing some other buffer (using leader x), the terminal comes into view and blocks buffer switching (tab, s-tab, and by mouse).

**To Reproduce**
1. Have a few buffers open
2. Launch terminal buffer and then hide it using `<leader>x`
3. Navigate between buffers
4. Close a buffer using <leader>x
5. Terminal buffer is re-activated and takes over the screen.

**Expected behavior**
I expect the hidden terminal to stay that way until it has been explicitly unhidden using the hidden terminal picker (telescope).

**Desktop (please complete the following information):**
- Windows 11
- Windows preview terminal
- WSL2 ubuntu 20.04
- neovim 0.5.0

**Comment by Diego77777777777** [comment]
> **Describe the bug**
> A hidden terminal buffer gets activated after closing some other buffer (using leader x), the terminal comes into view and blocks buffer switching (tab, s-tab, and by mouse).
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Have a few buffers open and high an volume that 100%
> 2. Launch terminal buffer and then hide it using `<leader>x`[]sdf)
> 3. Navigate between buffers
> 4. Close a buffer using <leader>x
> 5. Terminal buffer is re-activated and takes over the screen.
> 
> **Expected behavior**
> I expect the hidden terminal to stay that way until it has been explicitly unhidden using the hidden terminal picker (telescope).****Flak_
> 
> 
> **Desktop (please complete the following information):**
> - Windows 11
> - Windows preview terminal
> - WSL2 ubuntu 20.04
> - neovim 0.5.0
>

**Comment by Diego77777777777** [comment]
Que te parece

**Comment by G-Rowell** [comment]
Hi @marwan38,

This is likely an issue with my code, I'll look into this tonight!


G

**Comment by G-Rowell** [comment]
Hi @marwan38,

I couldn't replicate this issue, I tried a few things including:

1. `nvim` inside of the ~/.config/nvim/` directory
2. `:e LICENSE` to open the license text file
3. `:e README.md` to open the readme text file in a new buffer (same window, so it's 'full-screen')
4. `<leader> + w` to open a terminal in a new buffer (same window, so it's 'full-screen')
5. `jk` to exit terminal mode
6. `<leader> + x` to close (hide) the terminal buffer
`PROBLEM EXPECTED HERE` but the behavior seems fine I think?

I also tried this using splits for the two text files instead.

Could you elaborate a little more on how to replicate this? I'll be able to get it fixed ASAP as soon as I can properly replicate it!


G

**Comment by marwan38** [comment]
@G-Rowell I don't have the exact repro steps. You'll have to wait till I get it to happen again :(. @siduck76 mentioned that he knows what I'm talking about in discord. Maybe he knows how to repro.

**Comment by G-Rowell** [comment]
@marwan38 

Do you mean that I am not using the correct reproducing steps?

**Comment by marwan38** [comment]
@G-Rowell no, sorry. I forgot to mention that it's the closest to i could get to reproduce. Sid said he knew what I was talking about so I wasn't too fuss about it.

**Comment by marwan38** [comment]
@G-Rowell I think I reproduced it:

1. Have a hidden terminal buffer open
2. Have some random active buffer, one of your project files
3. Create a new tab with `<S-t>`
4. close the new tab `<leader>x`

**Comment by G-Rowell** [comment]
Hmmmm,

@marwan38 

Again, presume this still happens?
I'm happy to investigate this properly later this week?

**Comment by marwan38** [comment]
@G-Rowell Following up with https://github.com/NvChad/NvChad/issues/436#issuecomment-919637959 

@siduck76 I think would be able to give you a clearer answer for this one.

**Comment by siduck76** [comment]
@G-Rowell

https://user-images.githubusercontent.com/59060246/136479486-bb26a5b8-2a9a-4d85-bd10-27f5a963807f.mp4


- open nvim 
- open vertical terminal 
- close it (hide it by leader x )
- open a file 
- close the file's buffer 
- hidden terminal buffer will be visible

**Comment by pc-2198x** [comment]
I have a similar issue to the one @marwan38 brought up initially, instead of bringing up a new report, I will just attach it to this one. This may be user error on my end, as I am fairly new to NVChad and VIM in general.

### The Bug:
**This only happens when I open up a new terminal session and run `nvim` for the first time.**

https://user-images.githubusercontent.com/66924619/139497531-e197c6bb-f37b-4c8c-9e6c-f6272be7a937.mp4

**Expected**
When I close "test 2" buffer using Leader + x, it should show the "test 1" buffer. This is fairly common behavior among most editors with tabs.

**Actual**
When I close "test 2" buffer using Leader + x, it shows the "test 3" terminal instead of "test 1". I cannot use Tab to switch back to the "test 1" buffer. I have to either click the buffer tab to return to it  or open a new blank buffer using Shift + T and hit Tab to return to the "test 1" buffer. If I try to reproduce it again, I get the "Expected" behavior outlined above.

**Steps to reproduce:**
1. Open `nvim` and type "test 1" in the initial buffer tab.
2. Use Shift + T to open a new buffer tab and type "test 2".
3. Use Leader + h to open a new terminal session. Type "test 3".
4. Switch back to the buffer tab "test 2".
5. Close the buffer tab using Leader + x.
6. Terminal with "test 3" will be duplicated where "test 2" use to be.
7. Repeat steps 2-5
8. "test 1" buffer now shows as originally expected.

### Desktop:
Arch Linux:
`uname -a`:
```
Linux GigaArch 5.14.14-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 20 Oct 2021 21:35:17 +0000 x86_64 GNU/Linux
```
Terminal:
`kitty -v`:
```
kitty 0.23.1 created by Kovid Goyal
```
Neovim:
`nvim -v`
```                                                                                                     
NVIM v0.5.1

Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.1/build/config -I/build/neovim/src/neovim-0.5.1/src -I/usr/include -I/build/neovim/src/neovim-0.5.1/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.1/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by G-Rowell** [comment]
and if you mean, close (get rid of) a terminal buffer completely, that's possible too! :D

**Comment by siduck** [comment]
ohh if you can work on this issue in your free time then do it, its been on for ages now
