### ISSUE TITLE
Cannot set mapping

### ISSUE THREAD

**Issue by rafa-acioly** [NvChad/NvChad#423]
**Describe the bug**
After updating `NvChad`, when I try to open `nvim` I got the error saying:

```text
Cannot set mapping [ mode = 'n' | key = '' | cmd = '<C-w>h' ]                                                                                                                                                                                 
Cannot set mapping [ mode = 'n' | key = '' | cmd = '<C-w>l' ]                                                                                                                                                                                 
Cannot set mapping [ mode = 'n' | key = '' | cmd = '<C-w>k' ]                                                                                                                                                                                 
Cannot set mapping [ mode = 'n' | key = '' | cmd = '<C-w>j' ]  
```

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 20.04 (Focal)
 - Terminator
 - NVIM v0.5.0

**Comment by thiagodebastos** [comment]
I did some digging and it looks like the mappings were missing.
I'm not sure what is going on because according to git blame it looks like these changes have existed for 7 days but when I updated just now, I can see that the mappings were just added in:

https://github.com/NvChad/NvChad/blob/main/lua/chadrc.lua#L146-L149

**Comment by G-Rowell** [comment]
Ahhh, ty for following up!
Sorry we couldn't get here in time

G
