### ISSUE TITLE
Transition from init.vim

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#481]
First, thank you for all the great work! I have spent the last few days becoming acquainted and have a few questions about how to transition from the `init.vim` I have cultivated over the last few years (wasn't sure whether a bug report or feature request was more appropriate).

- how can I add plugins? for example, `iron.nvim` for REPLs
- how should I configure plugins that I add?
- how should I configure the default plugins?
- how can I add general mappings and autocmds? i.e. pipe for vertical split or spell check for plain text,  markdown, tex files
- is there any integration with `wal.vim` for themes?

Thank you so much!

**Comment by Theory-of-Everything** [comment]
If you want a fully 100% lua way to do everything, I got what you need (although maybe opening an issue isn't the best of ideas). So to answer a few of your qestions:
- 1:
nvim plugins are managed (in lua) with [packer.nvim](https://github.com/wbthomason/packer.nvim) its a really nice plugin manager and can install both lua and vimscript plugins. you can check out the repo fo instructions on how to add plugins. you can also use vim-plug or whatever, but they dont play nicely with lua.
- 2:
pick your lanuage: vimscript (supports everything) or lua (supports some stuff) while they are both great, there are some drawbacks with using lua, mainly that it doesn't support autocmds and colorschemes/syntax/hl. generally, you can find configraution examples/guide on the repo or help text for the plugin
- 3:
kinda just like you do it in vim, but converting that to the lua api
- 4:
You can add custom mappings, you can use `vim.api.nvim_set_keymap()` (that is for lua) or you can define it in vimscript with `vim.cmd`. autocommands arent natively supported in the nvim lua api, so you have to do it in vimscript
- 5:
I would assume it would work, its only a matter of trying it out

**Comment by danjenson** [comment]
Thanks for the response! I suppose I'm interested in particulars, i.e. are there conventions when using nvchad? Should I add/edit the default configs in my clone of the repo? Will those changes get nuked when I update nvchad? Thanks!

**Comment by Theory-of-Everything** [comment]
It really depends, I know for fact that if you do make customizations to nvchad, they will kinda get nuked because of a big refactor coming up (#465). 
While my personal opinion, I think that there is a lot of code in NvChad (at least for my liking) and I myself have a hard time understanding everything thats going on under the hood. But despite that, NvChad is a really solid config thats kinda like a "just works" nvim config (and it works pretty well for that).  You *could* clone and edit the repo, but since there are a lot of little parts that all depend on each other, unless you know what you are doing, you might end up tripping up.
There are also quite a few other configurations that exist as well that may (or may not) cater to your needs. [neovimcraft](https://neovimcraft.com) is a great place to look for other configs (especially because it has a preconfigured-configurations tag).

In the end, its up to you what you want to do, Im just giving a few of my ideas and opinions.

**Comment by siduck76** [comment]
@Theory-of-Everything Sorry for letting the config get complex! I sometimes used to get spooked when I looked at it lol but yea once (#465) gets merged , I will surely add a good config walkthrough + explanation in the docs :)

**Comment by Theory-of-Everything** [comment]
Yeah no worries @siduck76! Its really just a me thing. Definitely getting some good documentation might help alleviate some of the confusion.

**Comment by G-Rowell** [comment]
@danjenson 

The big custom overhaul PR #465 is merged!

There are comments inside of `core/default_config.lua` (don't modify this file)

And comments inside of `custom/example_init.lua` & `custom/example_chadrc.lua`, these are the places to look!


G

**Comment by siduck76** [comment]
@danjenson  huge changes have been made  for integrating docs now , check the docs!

https://nvchad.github.io/config
