### ISSUE TITLE
Preserve folders in custom directory when updating

### ISSUE THREAD

**Issue by peppapig450** [NvChad/NvChad#569]
**Is your feature request related to a problem? Please describe.**
When I updated NvChad, my plugins folder in the custom directory containing my lspconfig and null-ls configurations was deleted. 

**Describe the solution you'd like**
Preserve the entire custom directory when updating NvChad.

**Describe alternatives you've considered**
I am not sure if this is possible but maybe if there is any directories in the custom directory preserve them (pretty much the same thing as above but slightly different)

**Additional context**
I tried to implement this myself but I couldn't figure out how the update function actually works , probably because I am still very new at lua.

**Comment by siduck76** [comment]
> **Is your feature request related to a problem? Please describe.** When I updated NvChad, my plugins folder in the custom directory containing my lspconfig and null-ls configurations was deleted.
> 
> **Describe the solution you'd like** Preserve the entire custom directory when updating NvChad.
> 
> **Describe alternatives you've considered** I am not sure if this is possible but maybe if there is any directories in the custom directory preserve them (pretty much the same thing as above but slightly different)
> 
> **Additional context** I tried to implement this myself but I couldn't figure out how the update function actually works , probably because I am still very new at lua.

I dont think that should happen ._.

**Comment by siduck76** [comment]
https://user-images.githubusercontent.com/59060246/138385909-faeffdc6-68d0-433d-bc85-7b5ec259ea7c.mp4

**Comment by siduck76** [comment]
> Idk then cuz when I did it on Ubuntu vm it deleted it, but on my mac I didn't. Sorry for wasting your time.

no worries , if you could reproduce the issue then I could help more!

**Comment by abalmos** [comment]
> Idk then cuz when I did it on Ubuntu vm it deleted it, but on my mac I didn't. Sorry for wasting your time.

How old was the Ubuntu NvChad install? Past versions of the updater would have deleted extra folders.

**Comment by peppapig450** [comment]
Couldn't have been older then a week since it's running Impish which was released one week ago exactly.

**Comment by zbirenbaum** [comment]
> can you make this issue reproducible? I dont face this on linux

I'm running arch but every time I've tried to use the update tool it has caused errors or deleted my configs too. Admittedly, that's probably due to me fixing a couple of bugs outside of custom, and then just running git pull after the insane number of errors and merge conflicts I got running the update tool. After I messed up making backups last time I stopped using the tool or pulling and started checking the repo for updates I care about and wget/manual merge.

**Comment by siduck** [comment]
> > can you make this issue reproducible? I dont face this on linux
> 
> I'm running arch but every time I've tried to use the update tool it has caused errors or deleted my configs too. Admittedly, that's probably due to me fixing a couple of bugs outside of custom, and then just running git pull after the insane number of errors and merge conflicts I got running the update tool. After I messed up making backups last time I stopped using the tool or pulling and started checking the repo for updates I care about and wget/manual merge.

If your config was older than the PR that introduced the custom folder then you'll face issues!

**Comment by se7en-x230** [comment]
I face once in a while the same problem and I fixed it with a alias.
`nvchad="rm -rf ~/.config/nvim && rm -rf ~/.local/share/nvim ; git clone https://github.com/NvChad/NvChad ~/.config/nvim ; ln -s ~/.config/chadrc.lua ~/.config/nvim/lua/custom/; nvim +'hi NormalFloat guibg=#1e222a' +PackerSync"`

Keeping my chadrc.lua elsewhere and linking it back after removing...

**Comment by zbirenbaum** [comment]
> > > can you make this issue reproducible? I dont face this on linux
> > 
> > 
> > I'm running arch but every time I've tried to use the update tool it has caused errors or deleted my configs too. Admittedly, that's probably due to me fixing a couple of bugs outside of custom, and then just running git pull after the insane number of errors and merge conflicts I got running the update tool. After I messed up making backups last time I stopped using the tool or pulling and started checking the repo for updates I care about and wget/manual merge.
> 
> If your config was older than the PR that introduced the custom folder then you'll face issues!

Haha! I've been around here for a while, believe me the migration to using the custom dir was an adventure, but it was one I had the pleasure of only having to take once and a long time ago. I have been using the custom dir since a couple of days after it came out.



> I face once in a while the same problem and I fixed it with an alias. `nvchad="rm -rf ~/.config/nvim && rm -rf ~/.local/share/nvim ; git clone https://github.com/NvChad/NvChad ~/.config/nvim ; ln -s ~/.config/chadrc.lua ~/.config/nvim/lua/custom/; nvim +'hi NormalFloat guibg=#1e222a' +PackerSync"`
> 
> Keeping my chadrc.lua elsewhere and linking it back after removing...


This is a great idea and is a much lower hassle way of doing management,  plus will make uploading my config files to git a lot less complicated. Speaking of which it has been months and I should really, really upload soon. Considering that I already wrote a script to swap where the ~/.config/nvim link points to I'm honestly kinda kicking myself for not thinking of this. Kudos to you though and I would recommend keeping your custom dir elsewhere and symlinking it into your nvchad dir like he does to anyone who comes here while waiting on a fix.

**Comment by peppapig450** [comment]
There doesn't need to be a fix though it happens once only.
