### ISSUE TITLE
Package NvChad as .tar.gz

### ISSUE THREAD

**Issue by peppapig450** [NvChad/NvChad#623]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
If we used ci/cd to package NvChad as .tar.gz whenever a commit or something happened it would probably be easy to submit it to package manager's in the future. (could probably submit it to the AUR to start with)

**Describe alternatives you've considered**
None 

**Additional context**
The only thing is I don't know if this is will work for installing it

**Comment by siduck** [comment]
oh idk how ci/cd works, it should package the master branch to .tar.gz whenever there are changes in the main branch.

**Comment by peppapig450** [comment]
I'll work on figuring out how it works tomorrow. Still doing homework rn lol

**Comment by peppapig450** [comment]
small update: im getting the hang of making a pkgbuild for the aur.
not sure about other distributions besides arch. maybe an install script?

**Comment by siduck** [comment]
> small update: im getting the hang of making a pkgbuild for the aur. not sure about other distributions besides arch. maybe an install script?

we had an install script before but it felt bloated and un-needed so we removed it

**Comment by G-Rowell** [comment]
@peppapig450 @siduck 
So I'm not really sure if we should package this,
I've done a lot of reading to check.

The main reason being:
we don't need to compile anything with NvChad, not now, not ever.

---

This is because NvChad is just a config for NeoVim,
wheras NeoVim is an application which is compiled out of Lua & C (etc...).

Thoughts?
Please correct if I'm wrong, but doubtful of the value of this.

Galen

**Comment by siduck** [comment]
I agree

**Comment by peppapig450** [comment]
https://aur.archlinux.org/packages/lunarvim-git/
lunarvim is packaged so idk

**Comment by siduck** [comment]
> https://aur.archlinux.org/packages/lunarvim-git/ lunarvim is packaged so idk

we are not lunarvim!! :rage: :laughing: :rocket:

**Comment by G-Rowell** [comment]
@peppapig450 

I think there is a very big difference between NvChad & LunarVim


LunarVim uses a different config location,
Uses about 30 more dependencies (incl. npm & yarn),
It basically attempts to do absolutely everything for web dev,
They have to have an install script due to all this complexity.


I respect their work, though they have quite a different approach compared to us.

Does this explain my reasoning a little better?
