### ISSUE TITLE
The style slant of statuesline shows abnormally

### ISSUE THREAD

**Issue by GitHubNeko** [NvChad/NvChad#738]
**Describe the bug**
Exception when I switch styles of statuslines

**Screenshots**
![Screenshot_20220122_162400](https://user-images.githubusercontent.com/83487691/150630876-f127741c-7ffe-42a0-88ec-9bf0f4dfe37a.jpg)

**Desktop (please complete the following information):**
 - Operating System：Android
 - Terminal：Termux
 - Version of Neovim：0.6.1-1

**Configuration content**

```lua
local M ={}

M.ui = {
   theme = "onedark",
}

M.plugins = {
   options = {
      statusline = {
         style = "slant",
      },
   },
}

return M
```

**Comment by siduck** [comment]
its normal here 
![image](https://user-images.githubusercontent.com/59060246/150633148-5a72efd7-6a2b-4156-ab4e-563f1966faa4.png)

**Comment by GitHubNeko** [comment]
> its normal here ![image](https://user-images.githubusercontent.com/59060246/150633148-5a72efd7-6a2b-4156-ab4e-563f1966faa4.png)

I think my font is fine, but why is there an error in Neovim?
![Screenshot_20220122_174024](https://user-images.githubusercontent.com/83487691/150633412-9dc8ce33-826b-4c15-b357-d4d02afe236f.jpg)

**Comment by GitHubNeko** [comment]
> its normal here ![image](https://user-images.githubusercontent.com/59060246/150633148-5a72efd7-6a2b-4156-ab4e-563f1966faa4.png)

I tried to modify the default configured icon, it can be displayed normally, which is very strange
![Screenshot_20220122_175153](https://user-images.githubusercontent.com/83487691/150633764-1a81a1df-5fc9-4cc5-83a3-91ff521f58f6.jpg)
![Screenshot_20220122_175210](https://user-images.githubusercontent.com/83487691/150633767-19a3fbd9-2c18-413a-87b0-bff559006ada.jpg)

**Comment by siduck** [comment]
did you do packersync

**Comment by GitHubNeko** [comment]
> 

yes  I implemented it :-(

**Comment by Akianonymus** [comment]
Can confirm, happening here too.

**Comment by siduck** [comment]
which terminal

**Comment by AlphaTechnolog** [comment]
I think it's a termux related problem, some terminals render different the glyph than others, and in another case the glyphs are different per Nerd Font, like Iosevka Nerd Font doesn't look equal than UbuntuMono Nerd Font or JetBrainsMono Nerd Font or CaskaydiaCove Nerd Font, all look the glyphs different depending on the terminal emulator.

> I experienced some issues too with the font rendering in termux

In this case I think it's a terminal emulator font rendering related issue, like this:

![Screenshot from 2022-01-22 16-42-47](https://user-images.githubusercontent.com/54639968/150654822-1ed1e5d4-5d96-4a90-9318-ac56bbade63a.png)

It's a comparison with alacritty and kitty terminal
> Alacritty is the right and kitty the left

In kitty the line spacing is different than alacritty and the font rendering are different, because this, it render the glyps more separated

Try changing your nerd font or trying changing the line_height in termux (honestly I don't know how to do it in termux)

**Comment by peppapig450** [comment]
you can change line spacing in kitty

**Comment by GitHubNeko** [comment]
It has been found that the problem exists in the font renderer, so it is closed
