### ISSUE TITLE
Lazy loading with cmp_nvim_lsp

### ISSUE THREAD

**Issue by kylix31** [NvChad/NvChad#740]
The default config in `lua/plugins/` doesn't work with some config that use `cmp_nvim_lsp` to set the capabilities for the lsp. 

When i try to use this in my `custom/plugins_config/lspconfig` (custom config):

```lua
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

-- Use a loop to conveniently call 'setup' on multiple servers and
-- map buffer local keybindings when the language server attaches
local servers = { 'sumneko_lua' }
for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
    flags = {
      debounce_text_changes = 150,
    }
  }
end
```

and:

```lua
M.plugins = {
   default_plugin_config_replace = {
      lspconfig = "custom.plugins_config.lspconfig",
   },
   options = {
     cmp = {
       lazy_load = false,
     },
   }
}
```

The module `cmp_nvim_lsp` is not found.

Only work if i remove the `after`s in the cascade, for example:

```lua
   use {
      "hrsh7th/nvim-cmp",
      disable = not plugin_settings.status.cmp,
      config = override_req("nvim_cmp", "plugins.configs.cmp", "setup"),
   }

   use {
      "L3MON4D3/LuaSnip",
      disable = not plugin_settings.status.cmp,
      wants = "friendly-snippets",
      config = override_req("luasnip", "plugins.configs.others", "luasnip"),
   }

   use {
      "saadparwaiz1/cmp_luasnip",
      disable = not plugin_settings.status.cmp,
   }

   use {
      "hrsh7th/cmp-nvim-lua",
      disable = not plugin_settings.status.cmp,
   }

   use {
      "hrsh7th/cmp-nvim-lsp",
      disable = not plugin_settings.status.cmp,
   }

   use {
      "hrsh7th/cmp-buffer",
      disable = not plugin_settings.status.cmp,
   }

   use {
      "hrsh7th/cmp-path",
      disable = not plugin_settings.status.cmp,
   }
```

**Comment by zbirenbaum** [comment]
It's because of the lazy_load = false more than likely. When I put that in my plugin options cmp broke for me too. Take the cmp table out of M.plugins.options and run packer sync. Out of curiosity, where did you read to do that? I've never seen that option before.

**Comment by siduck** [comment]
is this required? 

local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

cant you use the older capabilities that lspconfig provides ._.

**Comment by kylix31** [comment]
> It's because of the lazy_load = false more than likely. When I put that in my plugin options cmp broke for me too. Take the cmp table out of M.plugins.options and run packer sync. Out of curiosity, where did you read to do that? I've never seen that option before.

Here:
https://github.com/hrsh7th/cmp-nvim-lsp#setup

It's good to auto set the capabilities for each client.

Back to the subject, even remove the `options` doesn't work...

**Comment by GreatestOfAllTimee** [comment]
Make sense, no wonder why even one of the Neovim/NeovimLSP dev using this option [`nvim-lua/kickstart.nvim/init.lua#L225`](https://github.com/nvim-lua/kickstart.nvim/blob/9288f4adcb25ebc70dab2ba0cd6b910b1fde57bf/init.lua#L225)

**Comment by siduck** [comment]
cmp is heavy at lazy loading so we lazy loaded it. Only thing we can do is load lspconfig after cmp

**Comment by siduck** [comment]
do lazy_load = false for cmp and packersync , lemme know if this works

**Comment by siduck** [comment]
@kylix31  https://github.com/NvChad/NvChad/issues/748

**Comment by siduck** [comment]
@kylix31 it should work now!

**Comment by zbirenbaum** [comment]
So I was reminded of this and became very curious exactly what lsp capabilities this added and which functionalities it enabled while refactoring, organizing, and adding some features to the lsp portion of my config, so I did some looking into it. 

This is going to be a bit of a long explanation, but the end answer is: Not lazy loading to run that function is absolutely pointless, you already had those capabilities you were adding, and the module you are requiring lazy loads cmp anyways. You are slowing your startup for exactly 0 reason. The only reason you got errors was due to the load order in init.lua more than likely. If you wanted to, you could load just cmp-nvim-lsp without loading cmp before the lsp and it would almost certainly work, although it may cause a race condition with the autocmd I'll mention below, but I don't know enough about how packer works to say for sure.

Here's the proof:
So first, I looked into the code of the cmp-nvim-lsp, and here is the source for the update_capabilities function.  
```
M.update_capabilities = function(capabilities, override)
  override = override or {}

  local completionItem = capabilities.textDocument.completion.completionItem

  completionItem.snippetSupport = if_nil(override.snippetSupport, true)
  completionItem.preselectSupport = if_nil(override.preselectSupport, true)
  completionItem.insertReplaceSupport = if_nil(override.insertReplaceSupport, true)
  completionItem.labelDetailsSupport = if_nil(override.labelDetailsSupport, true)
  completionItem.deprecatedSupport = if_nil(override.deprecatedSupport, true)
  completionItem.commitCharactersSupport = if_nil(override.commitCharactersSupport, true)
  completionItem.tagSupport = if_nil(override.tagSupport, { valueSet = { 1 } })
  completionItem.resolveSupport = if_nil(override.resolveSupport, {
    properties = {
      'documentation',
      'detail',
      'additionalTextEdits',
    }
  })

  return capabilities
end
```
All other aspects of  the plugin  are run via this autocmd in it's setup (cmp is required in M._on_insert_enter which would cause an error if cmp is not loaded at that point)
```
M.setup = function()
  vim.cmd([[
    augroup cmp_nvim_lsp
      autocmd!
      autocmd InsertEnter * lua require'cmp_nvim_lsp'._on_insert_enter()
    augroup END
  ]])
end
```
So not only can it be run without loading cmp before the lsp server startup, and, in fact, does so via the main function of the module being called by an  insert enter autocmd registered during setup, which also happens to be when cmp is lazy loaded.

Now, lets go back to that update capabilities function. If this looks familiar, that's because the exact same operations (and more) were performed in plugins.configs.lsp_config (prior to its removal in the lsp removal commit) here:

```
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.documentationFormat = { "markdown", "plaintext" }
capabilities.textDocument.completion.completionItem.snippetSupport = true
capabilities.textDocument.completion.completionItem.preselectSupport = true
capabilities.textDocument.completion.completionItem.insertReplaceSupport = true
capabilities.textDocument.completion.completionItem.labelDetailsSupport = true
capabilities.textDocument.completion.completionItem.deprecatedSupport = true
capabilities.textDocument.completion.completionItem.commitCharactersSupport = true
capabilities.textDocument.completion.completionItem.tagSupport = { valueSet = { 1 } }
capabilities.textDocument.completion.completionItem.resolveSupport = {
   properties = {
      "documentation",
      "detail",(prior to its removal in the lsp removal commit)
      "additionalTextEdits",
   },
}
```

Now naturally I thought "No way, it must be doing something else, maybe there's some obscure code in some lsp api or elsewhere that triggers when this is loaded first", so I wrote a lua script which iterates two tables and finds the keys which are in one, but not the other. I gave it
`require("cmp_nvim_lsp").update_capabilities(vim.lsp.protocol.make_client_capabilities())`
and
` vim.lsp.protocol.make_client_capabilities()`

Here is the result:

![image](https://user-images.githubusercontent.com/32016110/151280155-9ec540ad-484a-4b94-8d2b-f03ea170e7df.png)

So then I printed the tables to manually search for the values that are different and confirm to rule out any bugs in my code, and the only differences were the table values changed in the above code, which are also performed during lazy loading by the LSP config. I checked and the table generated by my config has the same keys and more (which I added manually) than the other.

I was going to include the relevant parts of those files but it was quite long and this is already pretty long post. If anyone feels that they really want irrefutable proof instead of just taking my word for it, however, I will upload them.

**Comment by siduck** [comment]
does cmp's capabilities have any advantages over inbuilt capabilities?

**Comment by zbirenbaum** [comment]
From the plugin page: https://github.com/hrsh7th/cmp-nvim-lsp

Language servers provide different completion results depending on the capabilities of the client. Neovim's default omnifunc has basic support for serving completion candidates. nvim-cmp supports more types of completion candidates, **_so users must override the capabilities sent to the server such that it can provide these candidates during a completion request. These capabilities are provided via the helper function require('cmp_nvim_lsp').update_capabilities_**

There are definite benefits and its a feature I would want to have functional in my config, all I am saying is that there are multiple ways to get it up and running, and not lazy loading is easily the most inefficient and ill advised of them.

**Comment by siduck** [comment]
for now you can just change the capabilities variable in your custom lspconfig 
![image](https://user-images.githubusercontent.com/59060246/151300168-734f62cd-5505-44ff-b217-4c4924ae45f1.png)

**Comment by zbirenbaum** [comment]
Wait did you add back in lsp stuff @siduck? I must have missed that

**Comment by siduck** [comment]
> Wait did you add back in lsp stuff @siduck? I must have missed that

its already added, I reverted that commit ( which removed lsp and cmp ) yesterday xD

**Comment by zbirenbaum** [comment]
Ngl kinda sad I fixed a bunch of stuff in my loading order and got my startup speed to sub 40ms :(

**Comment by siduck** [comment]
> Ngl kinda sad I fixed a bunch of stuff in my loading order and got my startup speed to sub 40ms :(
 
 loading order of cmp plugins and lspconfig?

**Comment by zbirenbaum** [comment]
That and a couple other things. Right now it's working but I run into strange issues every once in a while on sync, usually due to impatient though. Once I have finished looking through source code to determine absolute best ways of doing things I'll PR it all. I do have a change for treesitter that helps and is perfectly stable tho. I'll PR it in a few.

**Comment by siduck** [comment]
sure PR's for improving startuptime are very encouraged! :rocket:

**Comment by asher-gh** [comment]
> for now you can just change the capabilities variable in your custom lspconfig
> ![image](https://user-images.githubusercontent.com/59060246/151300168-734f62cd-5505-44ff-b217-4c4924ae45f1.png)

I'm getting the autocomplete options, but upon pressing enter, I'm getting this error:
```
E5108: Error executing lua ...hare/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/core.lua:413: attempt to index field 'snippet' (a bo
olean value)
stack traceback:
        ...hare/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/core.lua:413: in function <...hare/nvim/site/pack/packer/opt/nvim-cmp/l
ua/cmp/core.lua:374>
        ...site/pack/packer/opt/nvim-cmp/lua/cmp/utils/feedkeys.lua:51: in function <...site/pack/packer/opt/nvim-cmp/lua/cmp/util
s/feedkeys.lua:49>
```

**Comment by siduck** [comment]
@asher-gh enable snippets in status table of plugins table in chadrc and do packersync
