### ISSUE TITLE
Disable key mappings for removed plugins

### ISSUE THREAD

**Issue by neiromaster** [NvChad/NvChad#828]
I want to use coc.nvim instead of the built-in lsp, also for nvim-tree. I added a list of plugins in default_plugin_remove, but now nvim shows an error that there are no plugins for some key mappings. The map function from core.utils does not change the mappings for these keys, and the unmap function is missing.  

Perhaps it would be more correct to make the key mappings inside the configuration of a particular plugin.
For example like this:

```lua
{
  "phaazon/hop.nvim,
  event = "BufRead",
  config = function()
    map("n", "s", ":HopChar2<cr>")
    map("n", "S", ":HopWord<cr>")
  end,
},

```
Then when removing the plugin, the corresponding key mappings would also be automatically removed

**Comment by zbirenbaum** [comment]
A couple of things here:

First, are you really sure you want to use coc? Every feature it has and more is implemented in a more optimized way via the built-in with plugins.

Second, while putting mappings in their respective plugin's config files isn't a bad idea per se, and is a change I would be happy to implement if @siduck will sign off on it, there are much easier ways to solve your problem.

All that really needs to happen is for whatever plugin config you are loading to be loaded after the mapping is. An unmap function isn't necessary because any new mapping will overwrite the old.

If you have a ton of trouble getting it to override, the catch all guaranteed-to-work solution is to just make a your own mappings.lua file which you require from chadrc or something and wrap your mappings like so:

```
vim.schedule(function ()
    map("n", "s", ":HopChar2<cr>")
    map("n", "S", ":HopWord<cr>")
end)
```
Which will always 100% of the time override any existing mapping.

If you have a super up to date neovim, you can take advantage of the lua autocmd api merged a few hours ago, and the vim.keymap.set function merged quite a while ago to do something like I have here:

```
M.navigation = function ()
   vim.api.nvim_create_autocmd({
      event = {"VimEnter"},
      callback = function ()
         vim.keymap.set('n', '<c-l>', '$', {silent=true, noremap=true})
         vim.keymap.set('n', '<c-h>', '^', {silent=true, noremap=true})
         vim.keymap.set('c', '<c-c>', '<c-e>', {silent=true, noremap=true})
      end,
      once = true,
   })
end
```

The power of vim.keymap.set is that it lets you call lua functions like so:
`vim.keymap.set('n', '<C-o>', function () require("dap").step_out() end, opts)`

or to really illustrate the point:
```
local continue = function ()
   if vim.bo.filetype == "lua" and not require("dap").session() then
      require("osv").run_this()
   else
      require("dap").continue()
   end
end
vim.keymap.set('n', '<C-c>', function () continue() end, opts)
```

**Comment by neiromaster** [comment]
The nvim lsp does not support almost any code refactoring yet. I could not find any documentation on how to write them myself without spending X hours or days studying various plugins.

But I created the issue precisely in order to introduce a more convenient system of working with key mappings, so that you can store the entire configuration of specific plugins together, rather than in different files. If this is really planned in NvChad, then the question can be closed.

**Comment by siduck** [comment]
mappings of removed plugins wont load

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#use-default-mapping-for-another-command

**Comment by graciasc** [comment]
If you are trying to remove mappings to removed plugins.

[Remove Mappings](https://nvchad.com/config/Mappings)
