### ISSUE TITLE
Why I can't use zc keys to fold my code

### ISSUE THREAD

**Issue by U-DI-Page** [NvChad/NvChad#864]
I have run :set foldmethod=syntax in neovim,
But when I pressed zc, I get a error 'can't found fold'

Can you guys fold your code, how do you set it up?

<img width="680" alt="image" src="https://user-images.githubusercontent.com/14305674/156925296-ece1d354-8288-4809-8767-1076b4e1545a.png">

**Comment by siduck** [comment]
```
set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()
```
Then try zc

**Comment by siduck** [comment]
https://github.com/nvim-treesitter/nvim-treesitter#folding

**Comment by caniko** [comment]
> ```
> set foldmethod=expr
> set foldexpr=nvim_treesitter#foldexpr()
> ```
> 
> Then try zc

Where do I set this? This is very unclear, and alien, sorry.

**Comment by siduck** [comment]
@caniko  obviously custom init.lua, only you had read nvchad.com docs you wouldnt ask here!! also make sure to convert it to lua

**Comment by caniko** [comment]
#readthedocs, thanks.

**Comment by siduck** [comment]
> #readthedocs, thanks.

dont take it the rude way tho lol, currently its just me working on nvchad and all its docs etc, no core members so i kinda get annoyed when  users ask simple questions without reading the docs, ive warned even in the post-install neovim window in nvchad to read the docs!

**Comment by gregmulvaney** [comment]
> #readthedocs, thanks.

I got you  homie. Just paste this in your chadrc 

```lua
local vim = vim
local opt = vim.opt

opt.foldmethod = "expr"
opt.foldexpr = "nvim_treesitter#foldexpr()"
```

**Comment by siduck** [comment]
> > #readthedocs, thanks.
> 
> I got you homie. Just paste this in your chadrc
> 
> ```lua
> local vim = vim
> local opt = vim.opt
> 
> opt.foldmethod = "expr"
> opt.foldexpr = "nvim_treesitter#foldexpr()"
> ```

buddy it should be in custom/init.lua, not chadrc!! will work in chadrc too but its bad practice

**Comment by s-rog** [comment]
1. I did a fresh install on ubuntu/wsl
2. ran the mason install and lazy update commands
3. uncommented the treesitter block in plugins/init.lua
4. added the snippet above to custom/init.lua

I tried folding in lua and python files (parser installed) but always end up with no fold found.
Any help is appreciated, thanks!

Edit: treesitter correctly highlights code blocks though...

**Comment by siduck** [comment]
@s-rog  ask on our discord server, iirc i had to add an autocmd to make the folds appear on startup :thinking:

**Comment by ghost-in-the-zsh** [comment]
> > > #readthedocs, thanks.
> > 
> > 
> > I got you homie. Just paste this in your chadrc
> > ```lua
> > local vim = vim
> > local opt = vim.opt
> > 
> > opt.foldmethod = "expr"
> > opt.foldexpr = "nvim_treesitter#foldexpr()"
> > ```
> 
> buddy it should be in custom/init.lua, not chadrc!! will work in chadrc too but its bad practice

Would it also be bad practice if it gets done in `overrides.lua`, since we're overriding default options? What makes it best practice to do that in `init.lua` instead?

Thanks.

**PS:** The default setting worked for me in Python, but neither the default nor the edit above worked for me in Rust.

**Comment by siduck** [comment]
@ghost-in-the-zsh  just do it anywhere and load that anywhere in your main init.lua, i hope  you are using nvchad v2.5

**Comment by ghost-in-the-zsh** [comment]
> i hope you are using nvchad v2.5

I wasn't, but I'm migrating (and re-doing my setup) as I write this.

> @ghost-in-the-zsh just do it anywhere and load that anywhere in your main init.lua

I'd be a good idea if there were recommendations on locations where specific kinds of changes should be made in a way that helps minimize (ideally, avoid) conflicts with my local and/or custom setups when the upstream "starter" (and/or "main") repos get new releases.

As a simple example of what I mean, in v2.5, the file `lua/chadrc.lua` file is tracked from the upstream; it stores the custom theme the user chooses to use. So, just changing the theme locally from the upstream default causes a conflict. What's the best way to perform my local changes to avoid conflicts with, or breakages caused by, upstream?

I have read through the nvchad.com page, but, AFAIK, these are topics that are not covered there.

Thanks.

**PS:** If this side-tracked discussion would be better off in its own "issue", please let me know and I can follow up with that and move/copy this post over.

**Comment by siduck** [comment]
It won't cause any conflict, upstream modules are prefixed with nvchad

**Comment by ghost-in-the-zsh** [comment]
> It won't cause any conflict, upstream modules are prefixed with nvchad

I'm not clear on what you mean. The example I gave with `lua/chadrc.lua` file, which already has a diff for removing the default theme from upstream and replacing it with my own, is one simple case of what I mean. More local changes to content increase the likelihood of conflict, since we'd be editing the same files.

I hope this clarifies.

**PS:** The main reason I'm trying to be careful with this is that I'm tracking my local changes in my own dotfiles repo, with GNU Stow, and I'm trying to figure out how things should be organized, sym-linked, etc. to avoid problems.

**Comment by siduck** [comment]
> > It won't cause any conflict, upstream modules are prefixed with nvchad
> 
> I'm not clear on what you mean. The example I gave with `lua/chadrc.lua` file, which already has a diff for removing the default theme from upstream and replacing it with my own, is one simple case of what I mean. More local changes to content increase the likelihood of conflict, since we'd be editing the same files.
> 
> I hope this clarifies.
> 
> **PS:** The main reason I'm trying to be careful with this is that I'm tracking my local changes in my own dotfiles repo, with GNU Stow, and I'm trying to figure out how things should be organized, sym-linked, etc. to avoid problems.

starter repo's .git must be removed... its just an example on using nvchads main repo...


![image](https://github.com/NvChad/NvChad/assets/59060246/560bb983-79d1-403f-b312-51d1c3a26987)

**Comment by ghost-in-the-zsh** [comment]
Done. I missed changes to the install steps; was still thinking in terms of the former `custom` dir for local changes. I'm trying to figure out some other stuff now, but I'll try to go over some of the docs again first to see if I can understand what I'm missing. Thanks.

**Comment by s-rog** [comment]
> @s-rog ask on our discord server, iirc i had to add an autocmd to make the folds appear on startup 🤔

~Seeing as there have been numerous updates to nvhad since, does code folding still require this autocmd to work?
Any chance it can be added to github/docs? (PS. thanks for saving my wrists from traditional IDEs)~

Edit: My options were not set correctly (my foldmethod was manual), folding works!

**Comment by d4vidsha** [comment]
To help others on NvChad v2.5, this is my `./lua/options.lua`:

```lua
require "nvchad.options"

-- add yours here!

local o = vim.o
o.foldmethod = 'expr'
o.foldexpr = 'nvim_treesitter#foldexpr()'
```
