### ISSUE TITLE
Better escape mapping override doesn't work and custom options too

### ISSUE THREAD

**Issue by grihasmp5** [NvChad/NvChad#938]
Hi, installed NvChad a couple of days ago and trying to change a few things. In this case I am trying to change the better_escape default mapping and set the scrolloff option in the chadrc.lua  but both doesn't work. Am I doing it right ?
I tried running :packercompile and :packersync btw

 - Operating System -  MacOS 12.2
 - Terminal - Alacritty
 - Version of Neovim - 0.6.1
 - NvChad version - b21defd

EDIT: I found a way to set the scrolloff using `vim.opt.scrolloff` (not sure if it's the "right" way of doing this) but still can't find a way to override the better_escape settings other than by changing it inside the default settings

![Screenshot 2022-04-09 at 14 23 02](https://user-images.githubusercontent.com/69362855/162576296-ee5dbb2a-3fcd-4383-ab0a-2ee5e2dabc48.png)

**Comment by zbirenbaum** [comment]
Technically default_plugin_config_replace is supposed function if it takes a table, the config function in others for better_escape just didn't have it implemented. I wrote up a fix and pushed it. asshm's answer might work, or you could pass it a lua module string pointing to a file with that in it, but your original implementation should work now, as I tested it.

Not sure if this will really matter since its looking very likely custom will be removed soon, but at least until then the behavior should be consistent with the docs.
